# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SmartFhirDemo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SmartFhirDemo
  pod 'SMART', :git =>  'https://github.com/smart-on-fhir/Swift-SMART.git', :submodules => true

  target 'SmartFhirDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SmartFhirDemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
